# Build-time feature selection from Kconfig and the selected simulation target.

CONFIG_CPPFLAGS :=
NPC_RESET_PC := 0x30000000

ifneq ($(strip $(CONFIG_FAST_SIM)),y)
ifeq ($(strip $(CONFIG_TRACE)),y)
CONFIG_RETIRE_TRACE ?= y
endif
ifeq ($(strip $(CONFIG_ITRACE)),y)
CONFIG_DISASM := y
CONFIG_RETIRE_TRACE ?= y
endif
ifeq ($(strip $(CONFIG_FTRACE)),y)
CONFIG_RETIRE_TRACE ?= y
endif
ifeq ($(strip $(CONFIG_DIFFTEST)),y)
CONFIG_RETIRE_TRACE ?= y
endif
ifeq ($(strip $(CONFIG_WATCHPOINT)),y)
CONFIG_INTERACTIVE_SDB ?= y
CONFIG_RETIRE_TRACE ?= y
endif
CONFIG_LOG_FLUSH_EACH_WRITE ?= y
endif

ifeq ($(SIM_TARGET),npc)
CONFIG_CPPFLAGS += -DCONFIG_NPC_VIRTUAL_SOC
NPC_RESET_PC := 0xa0000000
endif

ifeq ($(SIM_TARGET),ysyxsoc)
NPC_RESET_PC := 0xa0000000
endif

CONFIG_CPPFLAGS += -DCONFIG_RESET_PC=$(NPC_RESET_PC)

ifeq ($(strip $(CONFIG_TRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_TRACE
endif
ifeq ($(strip $(CONFIG_ITRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_ITRACE
endif
ifeq ($(strip $(CONFIG_DISASM)),y)
CONFIG_CPPFLAGS += -DCONFIG_DISASM
endif
ifeq ($(strip $(CONFIG_FTRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_FTRACE
endif
ifeq ($(strip $(CONFIG_MTRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_MTRACE
endif
ifeq ($(strip $(CONFIG_DTRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_DTRACE
endif
ifeq ($(strip $(CONFIG_PCTRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_PCTRACE
endif
ifeq ($(strip $(CONFIG_RETIRE_TRACE)),y)
CONFIG_CPPFLAGS += -DCONFIG_RETIRE_TRACE
endif
ifeq ($(strip $(CONFIG_DIFFTEST)),y)
CONFIG_CPPFLAGS += -DCONFIG_DIFFTEST
endif
ifeq ($(strip $(CONFIG_INTERACTIVE_SDB)),y)
CONFIG_CPPFLAGS += -DCONFIG_INTERACTIVE_SDB
endif
ifeq ($(strip $(CONFIG_LOG_FLUSH_EACH_WRITE)),y)
CONFIG_CPPFLAGS += -DCONFIG_LOG_FLUSH_EACH_WRITE
endif
ifeq ($(strip $(CONFIG_WATCHPOINT)),y)
CONFIG_CPPFLAGS += -DCONFIG_WATCHPOINT
endif

BUILD_MODE_FILE := $(SIM_BUILD_DIR)/.selected_build_mode
BUILD_MODE_TEXT = SIM_TARGET=$(SIM_TARGET) BOARD=$(BOARD) NPC_RESET_PC=$(NPC_RESET_PC) VERILATOR=$(shell command -v $(VERILATOR)) VERILATOR_ROOT=$(VERILATOR_ROOT) VERILATOR_TRACE=vcd CONFIG_TRACE=$(CONFIG_TRACE) CONFIG_DISASM=$(CONFIG_DISASM) CONFIG_ITRACE=$(CONFIG_ITRACE) CONFIG_FTRACE=$(CONFIG_FTRACE) CONFIG_MTRACE=$(CONFIG_MTRACE) CONFIG_DTRACE=$(CONFIG_DTRACE) CONFIG_PCTRACE=$(CONFIG_PCTRACE) CONFIG_RETIRE_TRACE=$(CONFIG_RETIRE_TRACE) CONFIG_DIFFTEST=$(CONFIG_DIFFTEST) CONFIG_INTERACTIVE_SDB=$(CONFIG_INTERACTIVE_SDB) CONFIG_LOG_FLUSH_EACH_WRITE=$(CONFIG_LOG_FLUSH_EACH_WRITE) CONFIG_WATCHPOINT=$(CONFIG_WATCHPOINT)

.PHONY: FORCE check_config

FORCE:

check_config:
	@if [ ! -f .config ]; then \
		echo "ERROR: Configuration file .config is missing."; \
		echo "Please run 'make menuconfig' first."; \
		exit 1; \
	fi

$(BUILD_MODE_FILE): FORCE | $(SIM_BUILD_DIR)
	@printf '%s\n' "$(BUILD_MODE_TEXT)" | cmp -s - $@ || printf '%s\n' "$(BUILD_MODE_TEXT)" > $@
